name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: macos-latest
    name: Run tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
